apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gmx-app
  description: A 1&1 App
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: mohammad-ali_uics/gmx-app
  tags:
    - app
    - gmx
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
  # relations:
  #   - type: ownedBy
  #     targetRef: user:default/mohammad-ali_uics
spec:
  type: website
  owner: mohammad-ali_uics
  lifecycle: production
  system: project-x
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: project-x
  description: Handy tools to keep devs in the loop
spec:
  owner: dev-relations-team
  domain: devs
