apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-role-binding
subjects:
  - kind: ServiceAccount
    name: gmx-service-account # Change this to your actual service account name
    namespace: gmx-service-account # Change this to your actual namespace
roleRef:
  kind: ClusterRole
  name: gmx-app-access-role
  apiGroup: rbac.authorization.k8s.io
