apiVersion: v1
kind: Service
metadata:
  name: gmx-app-service
  namespace: gmx-service-account
spec:
  type: ClusterIP
  selector:
    app: gmx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
