import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import ModalNavigator from "./ModalNavigator";
import { FormProvider } from "./context/FormContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GMX App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <FormProvider>
          <div className="pt-10 ml-36">
            <ModalNavigator />
            <main>{children}</main>
          </div>
        </FormProvider>
      </body>
    </html>
  );
}
